services:
  handler:
    build:
      context: .
      target: handler
    restart: unless-stopped
    tty: true
    env_file:
      - .env
  gateway:
    build:
      context: .
      target: gateway
    restart: unless-stopped
    tty: true
    env_file:
      - .env
  cache:
    container_name: cache
    image: eqalpha/keydb:alpine
    restart: unless-stopped
    tty: true
    volumes:
      - cache-data:/data
      - ./config/cache/keydb.conf:/etc/keydb/keydb.conf
  database:
    container_name: database
    image: postgres:alpine
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    ports:
      - "5432:5432" # Expose the port to the host | Only if you want to access the database from the host
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  cache-data:
  database-data: